### ISSUE TITLE
Auto update workflow is broken

### ISSUE THREAD

**Issue by msfjarvis** [nix-community/flake-firefox-nightly#42]
First failing run is https://github.com/nix-community/flake-firefox-nightly/actions/runs/12051237330/job/33601826803#step:8:110

Here are the zipped logs from the run in case Actions cleans them up too quickly [logs_31397873841.zip](https://github.com/user-attachments/files/17955385/logs_31397873841.zip)

**Comment by colemickens** [comment]
I think this will be fixed with this https://github.com/mozilla/nixpkgs-mozilla/pull/333
